
trigger:
- master

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    
    steps:
    - script: echo build and push
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy job
    
    environment: 'emptyprod'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploying