
trigger:
- master

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    pool: default
    steps:
    - script: echo build and push
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy job
    pool: default
    environment: 'gopinathchexpressAKS.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploying